sudo: required

services:
  - docker

language: python
cache:
  pip: true
branches:
  only:
    - eb
    - master
git:
  depth: 3

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - export BEELINE_VENV=$PWD/virtualenvironment
  - virtualenv $BEELINE_VENV
  - $BEELINE_VENV/bin/pip install --upgrade awsebcli
  - mkdir -p ~/.aws
  - echo "[default]" > ~/.aws/config
  - echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
  - echo "region=ap-southeast-1" >> ~/.aws/config
  - echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
  - mkdir -p .elasticbeanstalk
  - sed -i -e "s/@TRAVIS_BRANCH/$TRAVIS_BRANCH/g" eb-config.yml
  - mv eb-config.yml .elasticbeanstalk/config.yml
script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export REPO=$TRAVIS_REPO_SLUG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo "Building image $REPO:$TAG"
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
  - sed -i -e "s/@TAG/$TAG/g" Dockerun.aws.json
  - cat Dockerun.aws.json
  - $BEELINE_VENV/bin/eb deploy beeline-landing-$TRAVIS_BRANCH --label $TRAVIS_COMMIT --message "$TRAVIS_COMMIT_MESSAGE" --timeout 25
