service: beeline-landing

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: ap-southeast-1
  stage: master
  runtime: nodejs6.10
  memorySize: 256

functions:
  lambda:
    handler: handler.main
    timeout: 30
    cors: true
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
