<template>
  <div class="details-page container">
    <div>
      <div>
        <strong>Requested Arrival Times</strong>
      </div>
      <div>
        Total number of requests: <strong>{{relatedRequests.length}}</strong>
      </div>
      <requests-time-histogram :requests="relatedRequests"
        :width="320" :height="350">
      </requests-time-histogram>
    </div>
    <GmapMap class="gmap"
        :center="{lat: 1.38, lng: 103.8}" :zoom="11"
        :options="{gestureHandling: 'greedy'}"
        ref="proposed-route-map">

      <RoutePathAndStops :stops="stops" />
      <SuggestionMarker v-for="(req, index) in relatedRequests"
        :key="`board-${index}`"
        :position="req.start" />
      <SuggestionMarker v-for="(req, index) in relatedRequests"
        :key="`alight-${index}`"
        :position="req.end" />
    </GmapMap>
  </div>
</template>

<style lang="scss">
 .details-page {
   min-height: 400px;
   display: flex;
   flex-direction: row;

   .gmap {
     flex: 1 1 auto;
   }
 }
</style>

<script>
import {keyBy} from 'lodash'
import axios from 'axios'
import querystring from 'querystring'
import RoutePathAndStops from '~/components/autogenerated/RoutePathAndStops'
import SuggestionMarker from '~/components/autogenerated/SuggestionMarker'
import RequestsTimeHistogram from '~/components/suggest/RequestsTimeHistogram'

export default {
  layout: 'landing',

  components: {
    RequestsTimeHistogram, RoutePathAndStops, SuggestionMarker
  },

  async asyncData (params) {
    const stopIndices = params.query.stops.split(',').map(s => parseInt(s))
    const path = stopIndices.join('/')

    const [stopDetailsReq, matchingRequestsReq] = await Promise.all([
      axios.get(
        'https://routing.beeline.sg/bus_stops'
      ),
      axios.get(
        `https://routing.beeline.sg/path_requests/${path}?` + querystring.stringify({
          maxDistance: 400, /* Should match setting in autogenerated.vue */
        })
      )
    ])

    return {
      allStops: stopDetailsReq.data,
      relatedRequests: matchingRequestsReq.data,
    }
  },

  data () {
    return {
      allStops: null,
      relatedRequests: null,
    }
  },

  computed: {
    allStopsById () {
      return this.allStops && keyBy(this.allStops, 'index')
    },

    stops () {
      if (this.allStopsById) {
        return this.$route.query
          .stops.split(',')
          .map(s => this.allStopsById[parseInt(s)])
          .map(s => {
            /* oops something is funny in our API */
            s.lat = s.coordinates[1]
            s.lng = s.coordinates[0]
            return s
          })
      }
    },
  }
}

</script>
