<template>

</template>


<script>

export default {
  layout: 'landing',

  async asyncData (params) {
    const stops = params.query.stops.split(',').map(s => parseInt(s))
    const path = stops.join('/')

    const [stopDetailsReq, matchingRequestsReq] = await Promise.all([
      axios.get(
        'https://routing.beeline.sg/bus_stops'
      ),
      axios.get(
        'https://routing.beeline.sg/path_requests/${path}?' + querystring.stringify({
          maxDistance: 400, /* Should match setting in autogenerated.vue */
        })
      )
    ])

    const stopsById = groupBy(stopDetailsReq.

    return {

    }
  }
}

</script>
