<template>
  <section class="suggestion-page container" v-if="suggestion && similarSuggestions && from && to" >
    <h1>{{from}} to {{to}}</h1>
    <h2>Suggestion by {{suggestion.email}}</h2>

    <div style="float: right; width: 350px">
      <p>
        There are {{similarSuggestions.length - 1}} other suggestions
        near this suggestion.
      </p>
      <transition name="expand">
        <div v-show="similarSuggestions.length > 0">
          <RequestsTimeHistogram :requests="similarSuggestions"
            :width="320" :height="320" />
        </div>
      </transition>
    </div>

    <p>
      This suggestion was made on
      {{dateformat(suggestion.createdAt, 'dddd, dd mmmm yyyy h:MM TT')}}
    </p>

    <h3>Running Routes Nearby</h3>

    <NearbyRoutes :options="{tags: JSON.stringify(['public']), maxDistance: MAX_WALKING_DISTANCE}"
        :start="pointToLatLng(suggestion.board)"
        :end="pointToLatLng(suggestion.alight)">
      <div slot="if-empty">
        There are no routes running nearby.
      </div>
      <template slot="route-link" slot-scope="s">
        <a target="_new"
           :href="'https://app.beeline.sg/tabs/route/' + s.route.id">
          ({{departureTimeFor(s.route)}}) {{s.route.from}}<br/>
          ({{arrivalTimeFor(s.route)}}) {{s.route.to}}<br/>
        </a>
      </template>
    </NearbyRoutes>

    <h3>Crowdstart Routes Nearby</h3>

    <NearbyRoutes :options="{tags: JSON.stringify(['crowdstart']), maxDistance: MAX_WALKING_DISTANCE}"
        :start="pointToLatLng(suggestion.board)"
        :end="pointToLatLng(suggestion.alight)"
        >
      <div slot="if-empty">
        There are no crowdstart routes nearby.
      </div>
      <template slot="route-link" slot-scope="s">
        <a target="_new"
           :href="'https://app.beeline.sg/tabs/crowdstart/' + s.route.id + '/detail'">
          ({{departureTimeFor(s.route)}}) {{s.route.from}}<br/>
          ({{arrivalTimeFor(s.route)}}) {{s.route.to}}<br/>
        </a>
      </template>
    </NearbyRoutes>

    <h3>Generate Some Routes</h3>

    <p>
      This is an experimental feature that tries to find some usable routes
      automatically. If you think the generated route suits you, let us know!
      We can create a crowdstart route based on it.
    </p>

    <p>
      <nuxt-link class="btn btn-default" :to="{
        path: '/autogenerated',
        query: {
          startLat: suggestion.board.coordinates[1],
          startLng: suggestion.board.coordinates[0],
          endLat: suggestion.alight.coordinates[1],
          endLng: suggestion.alight.coordinates[0],
          time: suggestion.time,
        }
        }">
        Ok... show me what you've got
      </nuxt-link>
    </p>

    <br clear="both" />

    <GmapMap class="stops-map" :center="mapCenter" :zoom="mapZoom">
      <!-- similar suggestions -->
      <GmapCluster :maxZoom="14">
        <GmapMarker v-for="suggestion in similarSuggestions"
          :key="suggestion.id"
          :position="{
            lat: suggestion.board.coordinates[1],
            lng: suggestion.board.coordinates[0],
            }"
          :icon="mapSettings.manWavingArmDarkIcon"
          :zIndex="1"
          />
      </GmapCluster>
      <GmapCluster :maxZoom="14">
        <GmapMarker v-for="suggestion in similarSuggestions"
          :key="suggestion.id"
          :position="{
            lat: suggestion.alight.coordinates[1],
            lng: suggestion.alight.coordinates[0],
            }"
          :icon="mapSettings.manWavingArmDarkIcon"
          :zIndex="1"
          />
      </GmapCluster>

      <!-- user's suggestion -->
      <GmapMarker
        :position="{
          lat: suggestion.board.coordinates[1],
          lng: suggestion.board.coordinates[0],
          }"
        :icon="mapSettings.manWavingArmIcon"
        :zIndex="10"
        />
      <GmapMarker
        :position="{
          lat: suggestion.alight.coordinates[1],
          lng: suggestion.alight.coordinates[0],
          }"
        :icon="mapSettings.manWavingArmIcon"
        :zIndex="10"
        />

      <CurvedOD
        :start="{lat: suggestion.board.coordinates[1], lng: suggestion.board.coordinates[0]}"
        :end="{lat: suggestion.alight.coordinates[1], lng: suggestion.alight.coordinates[0]}"
        :options="{
          icons: mapSettings.chevronIcons('#FF3863', 2.5),
          strokeColor: '#FF3863',
          strokeOpacity: 0.0,
          strokeWeight: 5,
          }"
        :zIndex="11"
        />
    </GmapMap>

    <PageDisqusThread />

  </section>
</template>

<style lang="scss">
.suggestion-page {
  .stops-map {
    width: 100%;
    height: 500px;
  }
}

.table {
  tr.active td {
    background-color: #FED;
  }
}
</style>

<script>
import querystring from 'querystring'
import axios from 'axios'
import dateformat from 'dateformat'
import pointToLatLng from '~/util/pointToLatLng'
import {getReverseGeocodeString} from '~/util/ReverseGeocoder'
import PageDisqusThread from '~/components/PageDisqusThread'
import NearbyRoutes from '~/components/suggest/NearbyRoutes'
import RequestsTimeHistogram from '~/components/suggest/RequestsTimeHistogram'
import MapSettings from '~/components/suggest/MapSettings'
import RequiresAuth from '~/mixins/RequiresAuth'
import CurvedOD from '~/components/suggest/CurvedOD'
import {sortBy} from 'lodash'

const MAX_WALKING_DISTANCE = 500
const MAX_DISTANCE = 2000

export default {
  props: ['id'],
  mixins: [RequiresAuth],
  head () {
// https://moz.com/blog/meta-data-templates-123
    return {
      meta: [
        {property: 'og:title', content: `Beeline Suggest - Find people going from ${this.from} to ${this.to}`},
        {property: 'og:type', content: 'article'},
        {property: 'og:url', content: `https://www.beeline.sg${this.$route.fullPath}`},
        {property: 'og:image', content: 'https://www.beeline.sg/images/feature_sgCrowdsource.png'},
        {property: 'og:description', content: `Join me and ${this.similarSuggestions && this.similarSuggestions.length}
          others on a Beeline! Together we can launch a shuttle bus!`},
      ]
    }
  },
  async asyncData ({params, error}) {
    // Here we do a dirty trick. For SEO purposes, we fetch the suggestion unauthenticated,
    // and display it first, along with all the similar suggestions
    const suggestion = (await axios.get(`https://api.beeline.sg/suggestions/web/${params.id}`)).data
    const [similarSuggestions, from, to] = (await Promise.all([
      axios.get(`https://api.beeline.sg/suggestions/web/similar?` + querystring.stringify({
        startLat: suggestion.board.coordinates[1],
        startLng: suggestion.board.coordinates[0],
        endLat: suggestion.alight.coordinates[1],
        endLng: suggestion.alight.coordinates[0],
        startDistance: MAX_DISTANCE,
        endDistance: MAX_DISTANCE,
      })).then(r => r.data),
      getReverseGeocodeString({
        lat: suggestion.board.coordinates[1],
        lng: suggestion.board.coordinates[0],
      }),
      getReverseGeocodeString({
        lat: suggestion.alight.coordinates[1],
        lng: suggestion.alight.coordinates[0],
      })
    ]))

    return {
      suggestion,
      similarSuggestions,
      from,
      to,
    }
  },
  data () {
    return {
      showAutogenerated: false,
      suggestion: null,
      similarSuggestions: null,
      from: null,
      to: null,
      mapCenter: {lat: 1.38, lng: 103.8},
      mapZoom: 11,
      MAX_WALKING_DISTANCE,
      MAX_DISTANCE,
    }
  },
  watch: {
    /* When the token is updated, reload the page to turn on/off anonymization */
    'auth.token': {
      immediate: true,
      async handler (t) {
        if (t) {
          this.suggestion = (await axios.get(`https://api.beeline.sg/suggestions/web/${this.$route.params.id}`, {
            headers: {authorization: `Bearer ${t}`}
          })).data
        }
      }
    }
  },
  computed: {
    mapSettings: () => MapSettings,
  },
  components: {
    PageDisqusThread, CurvedOD, RequestsTimeHistogram, NearbyRoutes
  },
  methods: {
    dateformat,
    pointToLatLng,

    departureTimeFor(route) {
      var tripStops = sortBy(route.trips[0].tripStops, ts => ts.time)
      return dateformat(new Date(tripStops[0].time).getTime() + 8 * 3600e3, 'h:MM TT', true)
    },
    arrivalTimeFor(route) {
      var tripStops = sortBy(route.trips[0].tripStops, ts => ts.time)
      return dateformat(new Date(tripStops[tripStops.length - 1].time).getTime() + 8 * 3600e3, 'h:MM TT', true)
    },
  }
}
</script>

<style>
</style>
