<template>
  <div>
    <h4 @click="opened = !opened">
      {{dateformat(parseInt(time), 'h:MM TT', true)}}
      ({{requests.length}})
    </h4>

    <ul v-if="opened">
      <li v-for="request in requests" :key="request.id">
        <EmailByRequestId :requestId="request.id" />
      </li>
    </ul>
  </div>
</template>

<script>
import EmailByRequestId from '~/components/autogenerated/EmailByRequestId.vue'
import dateformat from 'dateformat'

export default {
  props: ['requests', 'time'],
  components: {EmailByRequestId},
  data () {
    return {
      opened: false,
    }
  },
  methods: {dateformat}
}
</script>
