<template>
  <div>
    <div class="search-settings form-inline">
      <div>
        <label>
          Walking distance at start
          <input type="number" v-model="localSettings.startWalkingDistance" step="10"
            class="form-control"
            to="/search"/>
        </label>
      </div>
      <div>
        <label>
          Walking distance at end
          <input type="number" v-model="localSettings.endWalkingDistance" step="10"
            class="form-control"
            to="/search"/>
        </label>
      </div>
      <div>
        <label>
          Cluster radius at start
          <input type="number" v-model="localSettings.startClusterRadius" step="10"
            class="form-control"
            to="/search"/>
        </label>
      </div>
      <div>
        <label>
          Cluster radius at end
          <input type="number" v-model="localSettings.endClusterRadius" step="10"
            class="form-control"
            to="/search"/>
        </label>
      </div>
      <div>
        <label>
          Detour minutes
          <input type="number" v-model="localSettings.maxDetourMinutes" step="1"
            class="form-control"
            to="/search" />
        </label>
      </div>
      <div>
        Data Source
        <label>
          <input type="radio" value="ezlink" :checked="localSettings.dataSource == 'ezlink'"
            class="form-control" />
          EZ Link
        </label>
        <label>
          <input type="radio" value="suggestions" :checked="localSettings.dataSource == 'suggestions'"
            class="form-control"  />
          Beeline Suggestions
        </label>
      </div>
      <button class="btn btn-default" @click="updateSetting">Suggest something else!</button>
    </div>

    <!-- HACK: the second if condition forces the map to be initialized
    only when the map will be visible, thus avoiding rendering issues -->
    <template v-if="autogeneratedRoutes && $route.path.startsWith('/autogenerated')">
      Start with one of these routes!
      <proposed-route-viewer v-for="route in routes"
        :route="route"
        class="proposed-route">
      </proposed-route-viewer>
    </template>
    <template v-else>
      ... loading ...
    </template>
  </div>
</template>
<style>
.search-settings {
  border: solid 1px #888;
  padding: 0.5em;
  margin: 0.5em
}
.proposed-route {
  margin: 0.5em;
}
</style>
<script>
import { mapGetters, mapState, mapActions, mapMutations } from 'vuex'
import ProposedRouteViewer from '../components/proposed-route-viewer.vue';
import SimilarRequests from '../components/similar-requests.vue';
import RouteViewer from '../components/route-viewer.vue';
import MapPreview from '../components/map-preview.vue';
import geocode from '../utils/geocoder';
import _ from 'lodash';

export default {
  components: {
    ProposedRouteViewer,
    MapPreview,
    RouteViewer,
    SimilarRequests
  },
  data() {
    return {
      offset: 0,
      localSettings: _.cloneDeep(this.$store.state.autogenerateSettings)
    }
  },
  computed: {
    ...mapState(['origin', 'destination', 'autogeneratedRoutes',
    'autogenerateSettings']),
    routes() {
      return this.autogeneratedRoutes.slice(this.offset, 5)
    }
  },
  methods: {
    updateSetting() {
      this.$store.commit('setAutogenerateSettings', this.localSettings)
    }
  }
}
</script>
