<template>
  <div>
    <template v-if="crowdstartRoute">
      <h3>Timing not Suitable? Propose something else!</h3>
      <crowdstart-from-route :route="crowdstartRoute"
        ref="routeEditor">
      </crowdstart-from-route>

      <button class="btn btn-primary" @click="">Submit!</button>
    </template>
  </div>
</template>

<script>
import { mapGetters, mapState, mapActions, mapMutations } from 'vuex'
import CrowdstartFromRoute from '../components/crowdstart-from-route.vue';
import RouteViewer from '../components/route-viewer.vue';
import MapPreview from '../components/map-preview.vue';
import geocode from '../utils/geocoder';
import _ from 'lodash';

export default {
  components: {
    CrowdstartFromRoute,
    MapPreview,
    RouteViewer,
    CrowdstartFromRoute,
  },
  data() {
    return {
      offset: 0,
      localSettings: _.cloneDeep(this.$store.state.autogenerateSettings)
    }
  },
  computed: {
    ...mapState(['crowdstartRoute']),
    routes() {
      return this.autogeneratedRoutes.slice(this.offset, 5)
    }
  },
  methods: {
    updateSetting() {
      this.$store.commit('setAutogenerateSettings', this.localSettings)
    }
  }
}
</script>
