<template>
  <div>
    <template v-if="crowdstartRoute">
      <h3>Timing not Suitable? Propose something else!</h3>
      <crowdstart-from-route
        ref="routeEditor" @proposed-route-changed="proposedRoute = $event"
        :route="crowdstartRoute"
        @crowdstart-route-changed="$store.commit('crowdstartRoute', $event)">
      </crowdstart-from-route>

      <button class="btn btn-primary" @click="createRoute">Submit!</button>
    </template>
  </div>
</template>

<script>
import { mapGetters, mapState, mapActions, mapMutations } from 'vuex'
import CrowdstartFromRoute from '../components/crowdstart-from-route.vue';
import RouteViewer from '../components/route-viewer.vue';
import MapPreview from '../components/map-preview.vue';
import geocode from '../utils/geocoder';
import {latlngDistance} from '../utils/latlngDistance';
import _ from 'lodash';
import assert from 'assert';
import {getMsSinceMidnight} from '../utils/filters';

export default {
  components: {
    CrowdstartFromRoute,
    MapPreview,
    RouteViewer,
  },
  data() {
    return {
      offset: 0,
      localSettings: _.cloneDeep(this.$store.state.autogenerateSettings),
      stops: null,
      proposedRoute: null,
    }
  },
  created() {
    this.$http.get(process.env.BEELINE_API + '/stops')
    .then(r => r.json())
    .then(stops => this.stops = stops)
  },
  computed: {
    ...mapState(['crowdstartRoute', 'crowdstartRoutePolylinePath', 'crowdstartRouteStartTime', 'idToken']),
    routes() {
      return this.autogeneratedRoutes.slice(this.offset, 5)
    }
  },
  methods: {
    updateSetting() {
      this.$store.commit('setAutogenerateSettings', this.localSettings)
    },

    async createRoute() {
      var routeName = prompt('Give a name to this route.')

      if (!routeName)
        return;

      var defaultOptions = {
        headers: {
          authorization: `Bearer ${this.idToken}`
        }
      }

      var postRouteResponse = await this.$http.post(process.env.BEELINE_API + '/custom/userSuggestedRoutes/userRoutes', {
        name: routeName,
        busStops: this.crowdstartRoute.trips[0].tripStops.map(ts => ({
                  coordinates: ts.stop.coordinates,
                  arriveAt: getMsSinceMidnight(ts.time + this.crowdstartRouteStartTime)
                })),
        path: {
          type: "LineString",
          coordinates: this.crowdstartRoutePolylinePath.map(point => [point.lat, point.lng])
        }
        }, defaultOptions)

      assert.strictEqual(postRouteResponse.status, 200)
    }
  }
}
</script>
