<template>
  <form class="search-form" ref="searchForm">
    <div class="r1">
      <div class="c1">
        <h1>Search for a Ride!</h1>
        <div class="form-inline">
          <label>
            Origin
            <gmap-autocomplete
              label="Origin"
              placeholder="e.g. Pasir Ris"
              class="form-control"
              :value="originText"
              :bounds="mapSettings.Singapore"
              @place_changed="setOrigin(latLngFromPlace($event))" />
          </label>
        </div>

        <div class="form-inline">
          <label>
            Destination
            <gmap-autocomplete
              label="Destination"
              placeholder="e.g. Sandcrawler Building"
              class="form-control"
              :value="destinationText"
              :bounds="mapSettings.Singapore"
              @place_changed="setDestination(latLngFromPlace($event))" />
          </label>
        </div>

        <div>
          <label>
            Paste (index, lat,lng,lat,lng,count) here:
            <input type="text" @change="updateFromText" />
        </div>
      </div> <!-- c1: the input boxes -->


      <div v-if="similarRequests" class="c2">
        There are {{similarRequests.length}} similar requests in your area.
        <div style="width: 250px; height: 150px">
          <requests-time-histogram :requests="similarRequests"
            :height="150" :width="250" />
        </div>
      </div>

      <div class="c2">
        <p v-if="runningRoutes && runningRoutes.length > 0">
          Running routes found!
          <router-link to="/running" class="btn btn-success" tag="button">
            Book Now!
          </router-link>
        </p>
        <p v-if="crowdstartedRoutes && crowdstartedRoutes.length > 0">
          Crowdstarted routes found!
          <router-link to="/crowdstarted" class="btn btn-info" tag="button">
            Help it start!
          </router-link>
        </p>
        <p v-if="autogeneratedRoutes && autogeneratedRoutes.length > 0">
          Create your own route!
          <router-link to="/autogenerated" class="btn btn-warning" tag="button">
            See suggestions!
          </router-link>
        </p>
        <p>
          <loading-spinner :show="loadingRequests" />
        </p>
      </div> <!-- c2: the results area -->
    </div>

    <div class="map-preview-panes">
      <map-preview
        :center="origin"
        @position-updated="updateLatLng('origin', $event)"
        ref="mapPreview1"
        class="map-preview">
        <route-viewer :route="selectedRoute"
          v-if="selectedRoute">
        </route-viewer>
        <similar-requests
          :requests="similarRequests"
          :status-bus="$refs.mapPreview1"
        ></similar-requests>
      </map-preview>
      <map-preview :center="destination"
        @position-updated="updateLatLng('destination', $event)"
        ref="mapPreview2"
        class="map-preview">
        <route-viewer :route="selectedRoute"
          v-if="selectedRoute">
        </route-viewer>
        <similar-requests :requests="similarRequests"
          :status-bus="$refs.mapPreview2"
        ></similar-requests>
      </map-preview>
    </div>
  </form>
</template>

<style lang="scss">
.map-preview-panes {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;

  .map-preview {
    flex: 1 0 300px;
    height: 400px;
    margin: 1em;
  }
}
.r1 {
  display: flex;
  flex-direction: row;

  .c1, .c2 {
    flex: 1 1 33%;
  }
}
</style>

<script>
import mapSettings from '../components/mapSettings.js';
import { mapGetters, mapState, mapActions, mapMutations } from 'vuex'
import ExistingRouteViewer from '../components/existing-route-viewer.vue';
import SimilarRequests from '../components/similar-requests.vue';
import RouteViewer from '../components/route-viewer.vue';
import MapPreview from '../components/map-preview.vue';
import LoadingSpinner from '../components/loading-spinner.vue';
import RequestsTimeHistogram from '../components/requests-time-histogram.vue';
import geocode from '../utils/geocoder';

export default {
  props: ['origin', 'destination'],
  components: {
    ExistingRouteViewer,
    MapPreview,
    RouteViewer,
    SimilarRequests,
    RequestsTimeHistogram,
    LoadingSpinner
  },
  data() {
    return {
      mapSettings,
      originText: '',
      destinationText: '',
    }
  },
  computed: {
    ...mapState(['origin', 'destination', 'selectedRoute', 'similarRequests',
      'autogeneratedRoutes', 'crowdstartedRoutes', 'runningRoutes',
      'loadingRequests'])
  },
  methods: {
    ...mapMutations(['setOrigin', 'setDestination']),
    latLngFromPlace(place) {
      if (place.geometry) {
        return {
          lat: place.geometry.location.lat(),
          lng: place.geometry.location.lng(),
        }
      }
    },
    goNext() {
      this.$store.dispatch('processRequest')
    },
    updateLatLng(which, what) {
      if (which === 'origin') {
        this.setOrigin(what);
      } else if (which === 'destination') {
        this.setDestination(what)
      } else {
        throw new Error('`which` should be "origin" or "destination"')
      }

      // additionally reverse geocode
      geocode(what)
      .then(r => {
        this.$set(this, which + 'Text', r[0].formatted_address)
      })
    },
    updateFromText(event) {
      var s = event.target.value;

      var parts = s.split(/,/g)

      this.setOrigin({lat: parseFloat(parts[1]), lng: parseFloat(parts[2])})
      this.setDestination({lat: parseFloat(parts[3]), lng: parseFloat(parts[4])})
    }
  }
}
</script>
