<template>
  <form class="search-form" ref="searchForm">
    <div class="r1">
      <div class="c1">
        <h1>Search for a Ride!</h1>
        <div class="form-inline">
          <label>
            Origin
            <gmap-autocomplete
              label="Origin"
              placeholder="e.g. Pasir Ris"
              class="form-control"
              :value="originText"
              :bounds="mapSettings.Singapore"
              @place_changed="setOrigin(latLngFromPlace($event))" />
          </label>
        </div>

        <div class="form-inline">
          <label>
            Destination
            <gmap-autocomplete
              label="Destination"
              placeholder="e.g. Sandcrawler Building"
              class="form-control"
              :value="destinationText"
              :bounds="mapSettings.Singapore"
              @place_changed="setDestination(latLngFromPlace($event))" />
          </label>
        </div>

      </div> <!-- c1: the input boxes -->


      <div v-if="similarRequests" class="c2">
        There are {{similarRequests.length}} similar requests in your area.
        <div style="width: 250px; height: 150px">
          <requests-time-histogram :requests="similarRequests"
            :height="150" :width="250" />
        </div>
      </div>

      <div class="c2">
        <template v-if="runningRoutes">
          <p v-if="runningRoutes.length > 0">
            Running routes found!
            <router-link to="/running" class="btn btn-success" tag="button">
              Book Now!
            </router-link>
          </p>
          <p v-else>
            No running routes. Sorry!
          </p>
        </template>
        <template v-if="crowdstartedRoutes">
          <p v-if="crowdstartedRoutes.length > 0">
            Crowdstarted routes found!
            <router-link to="/crowdstarted" class="btn btn-info" tag="button">
              Help it start!
            </router-link>
          </p>
          <p v-else>
            No crowdstarted routes. Maybe you should start one?
          </p>
        </template>
        <template v-if="autogeneratedRoutes">
          <p v-if="autogeneratedRoutes.length > 0">
            Create your own route!
            <router-link to="/autogenerated" class="btn btn-warning" tag="button">
              See suggestions!
            </router-link>
          </p>
          <p v-else>
            Oops. No routes found! (Make a suggestion!)
          </p>
        </template>

        <div v-if="origin && destination && !suggestion.submitted">
          <hr/>
          Save your suggestion!
          This will help us suggest better routes.
          <p>
            <label>
              Arrival time at destination:
              <time-selector v-model="suggestion.time" />
            </label>
            <button class="btn btn-primary" @click="suggest"
              type="button" :disabled="suggestions && suggestions.length >= 5">
              Save Suggestion!
            </button>
          </p>
          <p v-if="suggestions && suggestions.length >= 5">
            You may not submit more than 5 suggestions!
            You may delete previous suggestions in the
            <router-link to="/suggest">Suggestions tab</router-link>
          </p>
        </div>
        <div v-else-if="suggestion.submitted">
          <hr/>
          Thank you! We will keep you notified
          if new routes appear near your place!
        </div>

        <p>
          <loading-spinner :show="loadingRequests" />
        </p>
      </div> <!-- c2: the results area -->
    </div>

    <div class="map-preview-panes">
      <map-preview
        :center="origin"
        @position-updated="updateLatLng('origin', $event)"
        ref="mapPreview1"
        class="map-preview">
        <route-viewer :route="selectedRoute"
          v-if="selectedRoute">
        </route-viewer>
        <similar-requests
          :requests="similarRequests"
          :status-bus="$refs.mapPreview1"
        ></similar-requests>
      </map-preview>
      <map-preview :center="destination"
        @position-updated="updateLatLng('destination', $event)"
        ref="mapPreview2"
        class="map-preview">
        <route-viewer :route="selectedRoute"
          v-if="selectedRoute">
        </route-viewer>
        <similar-requests :requests="similarRequests"
          :status-bus="$refs.mapPreview2"
        ></similar-requests>
      </map-preview>
    </div>
  </form>
</template>

<style lang="scss">
.map-preview-panes {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;

  .map-preview {
    flex: 1 0 300px;
    height: 400px;
    margin: 1em;
  }
}
.r1 {
  display: flex;
  flex-direction: row;

  .c1, .c2 {
    flex: 1 1 33%;
  }
}
</style>

<script>
import mapSettings from '../components/mapSettings.js';
import { mapGetters, mapState, mapActions, mapMutations } from 'vuex'
import ExistingRouteViewer from '../components/existing-route-viewer.vue';
import SimilarRequests from '../components/similar-requests.vue';
import RouteViewer from '../components/route-viewer.vue';
import MapPreview from '../components/map-preview.vue';
import LoadingSpinner from '../components/loading-spinner.vue';
import RequestsTimeHistogram from '../components/requests-time-histogram.vue';
import geocode from '../utils/geocoder';
import A0Lock from '../utils/login.js';
import TimeSelector from '../components/time-selector.vue';

export default {
  props: ['origin', 'destination'],
  components: {
    ExistingRouteViewer,
    MapPreview,
    RouteViewer,
    SimilarRequests,
    RequestsTimeHistogram,
    LoadingSpinner,
    TimeSelector
  },
  created() {
    this.fetchSuggestions();
  },
  data() {
    return {
      mapSettings,
      originText: '',
      destinationText: '',

      suggestion: {
        submitted: false,
        time: '',
      }
    }
  },
  watch: {
    origin() {
      this.suggestion.submitted = false;
    },
    destination() {
      this.suggestion.submitted = false;
    },
  },
  computed: {
    ...mapState(['origin', 'destination', 'selectedRoute', 'similarRequests',
      'autogeneratedRoutes', 'crowdstartedRoutes', 'runningRoutes',
      'loadingRequests', 'idToken', 'profile', 'suggestions']),
    ...mapGetters(['idTokenState', 'decodedIdToken'])
  },
  methods: {
    ...mapMutations(['setOrigin', 'setDestination']),
    ...mapActions(['fetchSuggestions']),
    latLngFromPlace(place) {
      if (place.geometry) {
        return {
          lat: place.geometry.location.lat(),
          lng: place.geometry.location.lng(),
        }
      }
    },
    goNext() {
      this.$store.dispatch('processRequest')
    },
    updateLatLng(which, what) {
      if (which === 'origin') {
        this.setOrigin(what);
      } else if (which === 'destination') {
        this.setDestination(what)
      } else {
        throw new Error('`which` should be "origin" or "destination"')
      }

      // additionally reverse geocode
      geocode(what)
      .then(r => {
        this.$set(this, which + 'Text', r[0].formatted_address)
      })
    },
    updateFromText(event) {
      var s = event.target.value;

      var parts = s.split(/,/g)

      this.setOrigin({lat: parseFloat(parts[1]), lng: parseFloat(parts[2])})
      this.setDestination({lat: parseFloat(parts[3]), lng: parseFloat(parts[4])})
    },
    suggest() {
      this.$store.commit('updateTimestamp')

      this.idTokenState
      .then((isValid) => {
        if (isValid) {
          return;
        } else {
          return A0Lock.logIn();
        }
      })
      .then(() => {
        var timeMs = this.suggestion.time;

        if (!timeMs) {
          throw new Error('Please select an arrival time!')
        }

        timeMs = timeMs.split(':')
        timeMs = 3600000 * timeMs[0] + 60000 * timeMs[1];

        return this.$http.post('http://localhost:8989/suggestions/web', {
          boardLat: this.origin.lat,
          boardLon: this.origin.lng,
          alightLat: this.destination.lat,
          alightLon: this.destination.lng,
          time: timeMs,
          email: this.decodedIdToken.email,
          emailVerification: {
            type: 'token',
            data: this.idToken
          }
        });
      })
      .then(() => {
        this.$store.dispatch('fetchSuggestions')
        this.suggestion.submitted = true;
      })
      .catch((err) => {
        alert(err.message)
        console.error(err)
      })
    }
  }
}
</script>
