<template>
  <div>
    <div v-if="profile">
      Logged in as {{profile.email}}.
      <button class="btn btn-default" @click="logOut">Log out</button>
    </div>
    <div v-else>
      <button class="btn btn-default" @click="logIn">Log in</button>
    </div>

    <ul class="nav nav-tabs">
      <router-link tag="li" active-class="active" to="/bulk">
        <a>Bulk</a>
      </router-link>
      <router-link tag="li" active-class="active" to="/search">
        <a>Search</a>
      </router-link>
      <router-link tag="li" active-class="active" to="/suggestions">
        <a>My Suggestions</a>
      </router-link>
      <router-link tag="li" active-class="active" to="/running">
        <a>Running Routes <span v-if="runningRoutes">({{runningRoutes.length}})</span></a>
      </router-link>
      <router-link tag="li" active-class="active" to="/crowdstarted">
        <a>Crowdstart Routes <span v-if="crowdstartedRoutes">({{crowdstartedRoutes.length}})</span></a>
      </router-link>
      <router-link tag="li" active-class="active" to="/autogenerated">
        <a>Autogenerated Routes <span v-if="autogeneratedRoutes">({{autogeneratedRoutes.length}})</span></a>
      </router-link>
      <router-link tag="li" active-class="active" to="/new">
        <a>New Crowdstart Route</a>
      </router-link>
      <li>
        <img src="/static/img/loading.svg" v-show="loadingRequests"
          class="loading-spinner" />
      </li>
    </ul>
    <keep-alive>
      <router-view></router-view>
    </keep-alive>
  </div>
</template>
<style lang="scss">
.loading-spinner {
  max-height: 1.5em;
}
</style>
<script>
import ProposedRouteViewer from './components/proposed-route-viewer.vue';
import ExistingRouteViewer from './components/existing-route-viewer.vue';
import CrowdstartFromRoute from './components/crowdstart-from-route.vue';
import MapPreview from './components/map-preview.vue';
import RouteViewer from './components/route-viewer.vue';
import SimilarRequests from './components/similar-requests.vue';
import {mapState} from 'vuex';

import querystring from 'querystring';
import scrollTo from './utils/scrollTo';
import A0Lock from './utils/login.js';

export default {
  name: 'app',
  components: {
    ExistingRouteViewer,
    MapPreview,
    ProposedRouteViewer,
    CrowdstartFromRoute,
    RouteViewer,
    SimilarRequests
  },
  computed: {
    ...mapState(['crowdstartedRoutes', 'runningRoutes', 'autogeneratedRoutes',
    'loadingRequests', 'token', 'profile'])
  },
  created() {
    this.$lock = A0Lock.lock;
    this.$lock.on('authenticated', (authResult) => {
      this.$lock.getProfile(authResult.idToken, (error, profile) => {
        if (error) {
          alert("Your email could not be verified");
          return;
        }

        this.$store.commit('setProfile', {profile, idToken: authResult.idToken});
      });
    })

    this.$store.dispatch('checkIdToken')
  },
  methods: {
    logIn() {
      A0Lock.logIn()
    },
    logOut() {
      A0Lock.logOut()
    },
  }
}

function latlngDistance(ll1, ll2) {
  var rr1 = [ll1[0] / 180 * Math.PI, ll1[1] / 180 * Math.PI]
  var rr2 = [ll2[0] / 180 * Math.PI, ll2[1] / 180 * Math.PI]

  var dx = (rr1[1] - rr2[1]) * Math.cos(0.5 * (rr1[0] + rr2[0]))
  var dy = rr1[0] - rr2[0]

  var dist = Math.sqrt(dx * dx + dy * dy) * 6371000
  return dist
}


</script>

<style lang="sass">
</style>
